services:
  mongodb:
    image: mongo:7.0
    container_name: realestate_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: realestate_api
    restart: always
    environment:
      - MONGO__CONNECTIONSTRING=mongodb://mongodb:27017
      - ASPNETCORE_URLS=http://+:8080
      - JWT_KEY=supersecretkeybase64==
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api
    container_name: realestate_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mongo_data:
